#!/bin/bash

if [[ -z $1 ]]; then
  echo -e "Add a size and the image to convert\n"
  echo -e "\tresize input.png (defaults to 40x40)"
  echo -e "\tresize [scale] input.png"
  echo -e "\tresize [scale] input.png output.png"
  echo -e "\tresize [scalex] [scaley] input.png output.png"
  exit;
fi

if [[ ! -z $4 ]]; then
  ffmpeg -i $3 -pix_fmt rgba -vf scale=$1:$2 $4
elif [[ ! -z $3 ]]; then
  ffmpeg -i $2 -pix_fmt rgba -vf scale=$1:$1 $3
elif [[ ! -z $2 ]]; then
  ffmpeg -i $2 -pix_fmt rgba -vf scale=$1:$1 $2"output.png"
else
  ffmpeg -i $1 -pix_fmt rgba -vf scale=40:40 $1"output.png"
fi
